project_id = "srp"

[api]
schemas = ["public", "graphql_public", "app_api", "app_private"]

[auth.third_party.firebase]
enabled = true
project_id = "env(FIREBASE_PROJECT_ID)"

[functions.syncUser]
verify_jwt = false

[functions.backendAction]
verify_jwt = false

[functions.cloudinaryWebhook]
verify_jwt = false

[functions.outboxWorker]
verify_jwt = false

[functions.processDeletionJobs]
verify_jwt = false

[functions.maintenanceCleanup]
verify_jwt = false
