export const BACKEND_ACTION_NAMES = [
  'cacheUserAvatar',
  'createAnnouncement',
  'createAnnouncementComment',
  'createComment',
  'createImageUploadSession',
  'createIssue',
  'deleteAnnouncement',
  'deleteAnnouncementComment',
  'deleteComment',
  'deleteIssue',
  'deleteUploadedImage',
  'finalizeImageUpload',
  'getAnnouncement',
  'getCurrentUserRole',
  'getIssue',
  'getNotificationReadState',
  'getNotificationSnapshot',
  'getPlatformDashboard',
  'getPushNotificationPreference',
  'getUserAvatarUrls',
  'listAnnouncementComments',
  'listAnnouncements',
  'listComments',
  'listIssues',
  'listNotifications',
  'listUserIssues',
  'markNotificationsOpened',
  'moderateIssueStatus',
  'recordPlatformVisit',
  'registerPushToken',
  'removeSupport',
  'resolveUploadImageUrls',
  'searchIssues',
  'setAnnouncementLike',
  'toggleSupport',
  'unregisterPushToken',
  'updateAnnouncement',
  'updateIssueResult',
  'updatePushNotificationPreferences',
] as const;

export type BackendActionName = typeof BACKEND_ACTION_NAMES[number];
