export const BACKEND_ACTION_NAMES = [
  'cacheUserAvatar',
  'createAnnouncement',
  'createAnnouncementComment',
  'createComment',
  'createImageUploadSessions',
  'createIssue',
  'deleteAnnouncement',
  'deleteAnnouncementComment',
  'deleteComment',
  'deleteIssue',
  'deleteUploadedImages',
  'finalizeImageUploads',
  'getAnnouncement',
  'getCurrentUserRole',
  'getIssue',
  'getNotificationReadState',
  'getNotificationUnreadHint',
  'getNotificationSnapshot',
  'getPlatformDashboard',
  'getPushNotificationPreference',
  'getUserAvatarUrls',
  'listAnnouncementComments',
  'listAnnouncements',
  'listComments',
  'listIssues',
  'listNotificationPages',
  'listUserIssues',
  'markNotificationsOpened',
  'moderateIssueStatus',
  'recordPlatformVisit',
  'registerPushToken',
  'removeSupport',
  'resolveUploadImageUrls',
  'searchIssues',
  'setAnnouncementLike',
  'toggleSupport',
  'unregisterPushToken',
  'updateIssueResult',
  'updatePushNotificationPreferences',
] as const;

export type BackendActionName = typeof BACKEND_ACTION_NAMES[number];
