/* This file is generated by scripts/generate-issue-categories.mjs. Do not edit manually. */

export type IssueReadAccess = 'school' | 'owner-admin' | 'reviewed-school';
export type IssueAuthorStorage = 'issue' | 'private';
export type IssueResponseDeadlineStart = 'created' | 'support-met' | 'none';
export type IssueUploadVisibility = 'private' | 'school';
export type IssueCommentVisibility = 'private' | 'school';
export type IssueCommentsEnabledWhen = 'readable' | 'public';

export interface IssueCategoryConfig {
  id: string;
  label: string;
  readAccess: IssueReadAccess;
  authorStorage: IssueAuthorStorage;
  support: {
    enabled: boolean;
    goal: number | null;
    deadlineDays: number | null;
    autoRejectUnmet: boolean;
  };
  responseDeadline: {
    start: IssueResponseDeadlineStart;
    days: number | null;
  };
  uploads: {
    visibility: IssueUploadVisibility;
  };
  comments: {
    visibility: IssueCommentVisibility;
    enabledWhen: IssueCommentsEnabledWhen;
  };
}

export const ISSUE_CATEGORIES = [
  {
    id: "public-issues",
    label: "公共議題",
    readAccess: "reviewed-school",
    authorStorage: "private",
    support: {
      enabled: true,
      goal: 50,
      deadlineDays: 14,
      autoRejectUnmet: true
    },
    responseDeadline: {
      start: "support-met",
      days: 7
    },
    uploads: {
      visibility: "school"
    },
    comments: {
      visibility: "school",
      enabledWhen: "public"
    }
  },
  {
    id: "rights-maintenance",
    label: "學生權益",
    readAccess: "owner-admin",
    authorStorage: "issue",
    support: {
      enabled: false,
      goal: null,
      deadlineDays: null,
      autoRejectUnmet: false
    },
    responseDeadline: {
      start: "created",
      days: 7
    },
    uploads: {
      visibility: "private"
    },
    comments: {
      visibility: "private",
      enabledWhen: "readable"
    }
  },
  {
    id: "facilities",
    label: "設備",
    readAccess: "school",
    authorStorage: "issue",
    support: {
      enabled: false,
      goal: null,
      deadlineDays: null,
      autoRejectUnmet: false
    },
    responseDeadline: {
      start: "created",
      days: 7
    },
    uploads: {
      visibility: "school"
    },
    comments: {
      visibility: "school",
      enabledWhen: "readable"
    }
  },
  {
    id: "test",
    label: "測試",
    readAccess: "school",
    authorStorage: "issue",
    support: {
      enabled: false,
      goal: null,
      deadlineDays: null,
      autoRejectUnmet: false
    },
    responseDeadline: {
      start: "created",
      days: 7
    },
    uploads: {
      visibility: "school"
    },
    comments: {
      visibility: "school",
      enabledWhen: "readable"
    }
  }
] as const satisfies readonly IssueCategoryConfig[];

export type IssueCategory = typeof ISSUE_CATEGORIES[number]['id'];

export const DEFAULT_ISSUE_CATEGORY: IssueCategory = ISSUE_CATEGORIES[0].id;
export const ISSUE_CATEGORY_IDS = ISSUE_CATEGORIES.map((category) => category.id) as IssueCategory[];
export const ISSUE_CATEGORY_LABELS = Object.fromEntries(
  ISSUE_CATEGORIES.map((category) => [category.id, category.label]),
) as Record<IssueCategory, string>;

const ISSUE_CATEGORY_BY_ID = ISSUE_CATEGORIES.reduce((lookup, category) => {
  lookup[category.id] = category;
  return lookup;
}, {} as Record<string, IssueCategoryConfig>);

export function isIssueCategory(value: unknown): value is IssueCategory {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(ISSUE_CATEGORY_BY_ID, value);
}

export function getIssueCategoryConfig(category: string | null | undefined): IssueCategoryConfig | null {
  if (typeof category !== 'string') return null;
  return ISSUE_CATEGORY_BY_ID[category] ?? null;
}

export function getIssueCategoryConfigOrDefault(category: string | null | undefined): IssueCategoryConfig {
  return getIssueCategoryConfig(category) ?? ISSUE_CATEGORY_BY_ID[DEFAULT_ISSUE_CATEGORY];
}

export function getIssueCategoryLabel(category: string | null | undefined): string {
  return getIssueCategoryConfig(category)?.label ?? String(category ?? DEFAULT_ISSUE_CATEGORY);
}

export function getIssueCategoryIdsByReadAccess(readAccess: IssueReadAccess): IssueCategory[] {
  return ISSUE_CATEGORIES
    .filter((category) => category.readAccess === readAccess)
    .map((category) => category.id);
}

export function getIssueCategoryIdsWithAutoRejectUnmetSupport(): IssueCategory[] {
  return ISSUE_CATEGORIES
    .filter((category) => category.support.autoRejectUnmet)
    .map((category) => category.id);
}

export function issueAllowsSupport(category: string | null | undefined): boolean {
  return getIssueCategoryConfigOrDefault(category).support.enabled;
}

export function issueRequiresReview(category: string | null | undefined): boolean {
  return getIssueCategoryConfigOrDefault(category).readAccess === 'reviewed-school';
}

export function issueStoresAuthorPrivately(category: string | null | undefined): boolean {
  return getIssueCategoryConfigOrDefault(category).authorStorage === 'private';
}

export function issueIsPrivateToOwner(category: string | null | undefined): boolean {
  return getIssueCategoryConfigOrDefault(category).readAccess === 'owner-admin';
}

export function getIssueUploadVisibility(category: string | null | undefined): IssueUploadVisibility {
  return getIssueCategoryConfigOrDefault(category).uploads.visibility;
}

export function getIssueSupportGoal(category: string | null | undefined): number | null {
  return getIssueCategoryConfigOrDefault(category).support.goal;
}

export function getIssueSupportDeadlineDays(category: string | null | undefined): number | null {
  return getIssueCategoryConfigOrDefault(category).support.deadlineDays;
}

export function issueAutoRejectsUnmetSupport(category: string | null | undefined): boolean {
  return getIssueCategoryConfigOrDefault(category).support.autoRejectUnmet;
}

export function getIssueResponseDeadlineStart(category: string | null | undefined): IssueResponseDeadlineStart {
  return getIssueCategoryConfigOrDefault(category).responseDeadline.start;
}

export function getIssueResponseDeadlineDays(category: string | null | undefined): number | null {
  return getIssueCategoryConfigOrDefault(category).responseDeadline.days;
}

export function issueAllowsCommentsForStatus(
  category: string | null | undefined,
  status: string | null | undefined,
): boolean {
  const config = getIssueCategoryConfigOrDefault(category);
  if (config.comments.enabledWhen === 'public') {
    return status !== 'under-review' && status !== 'review-rejected';
  }
  return true;
}
