// This file is generated automatically by scripts/generate-rate-limits.mjs.
// Do not edit this file manually.

export const RATE_LIMITS = {
  "issueCreateDaily": {
    "limit": 30,
    "message": "達到上限，明天才能再發。"
  },
  "commentCreateHourly": {
    "limit": 200,
    "message": "留言達到上限，稍後再試。"
  },
  "imageUploadDaily": {
    "limit": 200,
    "message": "今天的圖片上傳額度已用完。"
  },
  "loginSyncHourly": {
    "limit": 300,
    "message": "登入同步太頻繁，請稍後再試。"
  },
  "avatarCacheDaily": {
    "limit": 60,
    "message": "頭像更新太頻繁，請稍後再試。"
  },
  "supportToggleHourly": {
    "limit": 600,
    "message": "附議操作太頻繁，請稍後再試。"
  },
  "announcementLikeHourly": {
    "limit": 600,
    "message": "公告互動太頻繁，請稍後再試。"
  },
  "pushTokenWriteHourly": {
    "limit": 120,
    "message": "通知裝置設定太頻繁，請稍後再試。"
  },
  "backendActionReadHourly": {
    "limit": 900,
    "message": "讀取太頻繁，請稍後再試。"
  },
  "backendActionReadSecond": {
    "limit": 8,
    "message": "讀取太頻繁，請稍後再試。"
  },
  "backendActionWriteHourly": {
    "limit": 300,
    "message": "操作太頻繁，請稍後再試。"
  },
  "backendActionWriteSecond": {
    "limit": 3,
    "message": "操作太頻繁，請稍後再試。"
  },
  "backendActionSensitiveWriteHourly": {
    "limit": 120,
    "message": "操作太頻繁，請稍後再試。"
  },
  "backendActionSensitiveWriteSecond": {
    "limit": 2,
    "message": "操作太頻繁，請稍後再試。"
  },
  "backendActionAdminWriteHourly": {
    "limit": 180,
    "message": "管理操作太頻繁，請稍後再試。"
  },
  "backendActionAdminWriteSecond": {
    "limit": 2,
    "message": "管理操作太頻繁，請稍後再試。"
  },
  "backendActionUploadResolveHourly": {
    "limit": 300,
    "message": "圖片讀取太頻繁，請稍後再試。"
  },
  "backendActionUploadResolveSecond": {
    "limit": 4,
    "message": "圖片讀取太頻繁，請稍後再試。"
  },
  "backendHealthcheckMinute": {
    "limit": 120,
    "message": "服務檢查太頻繁，請稍後再試。"
  },
  "backendHealthcheckSecond": {
    "limit": 5,
    "message": "服務檢查太頻繁，請稍後再試。"
  },
  "cloudinaryWebhookMinute": {
    "limit": 300,
    "message": "圖片同步太頻繁，請稍後再試。"
  },
  "cloudinaryWebhookSecond": {
    "limit": 10,
    "message": "圖片同步太頻繁，請稍後再試。"
  },
  "workerRunMinute": {
    "limit": 30,
    "message": "背景處理太頻繁，請稍後再試。"
  },
  "workerRunSecond": {
    "limit": 2,
    "message": "背景處理太頻繁，請稍後再試。"
  },
  "imageUploads": {
    "issueMaxImages": 5,
    "announcementMaxImages": 5,
    "commentMaxImages": 1
  },
  "imageCompression": {
    "maxUploadKilobytes": 800,
    "maxUploadBytes": 819200,
    "maxSourceMegabytes": 20,
    "maxSourceBytes": 20971520,
    "maxDimension": 2000,
    "maxPixels": 16000000,
    "webpQuality": 0.85,
    "outputScales": [
      1,
      0.9,
      0.8,
      0.7,
      0.6,
      0.5,
      0.4
    ]
  }
} as const;

export type RateLimits = typeof RATE_LIMITS;
